// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: connected_accounts.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createConnectedAccount = `-- name: CreateConnectedAccount :one
insert into connected_accounts (user_id, provider, credentials)
values ($1::uuid, $2::text, $3::bytea)
returning id, user_id, provider, credentials, sync_cursor, status, created_at, updated_at
`

type CreateConnectedAccountParams struct {
	UserID      uuid.UUID `db:"user_id" json:"user_id"`
	Provider    string    `db:"provider" json:"provider"`
	Credentials []byte    `db:"credentials" json:"credentials"`
}

func (q *Queries) CreateConnectedAccount(ctx context.Context, arg CreateConnectedAccountParams) (ConnectedAccount, error) {
	row := q.db.QueryRow(ctx, createConnectedAccount, arg.UserID, arg.Provider, arg.Credentials)
	var i ConnectedAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Credentials,
		&i.SyncCursor,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteConnectedAccount = `-- name: DeleteConnectedAccount :execrows
delete from connected_accounts
where id = $1::bigint and user_id = $2::uuid
`

type DeleteConnectedAccountParams struct {
	ID     int64     `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteConnectedAccount(ctx context.Context, arg DeleteConnectedAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteConnectedAccount, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getConnectedAccount = `-- name: GetConnectedAccount :one
select id, user_id, provider, credentials, sync_cursor, status, created_at, updated_at
from connected_accounts
where id = $1::bigint
`

func (q *Queries) GetConnectedAccount(ctx context.Context, id int64) (ConnectedAccount, error) {
	row := q.db.QueryRow(ctx, getConnectedAccount, id)
	var i ConnectedAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Credentials,
		&i.SyncCursor,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveConnectedAccounts = `-- name: ListActiveConnectedAccounts :many
select id, user_id, provider, credentials, sync_cursor, status, created_at, updated_at
from connected_accounts
where status = 'active'
order by id
`

func (q *Queries) ListActiveConnectedAccounts(ctx context.Context) ([]ConnectedAccount, error) {
	rows, err := q.db.Query(ctx, listActiveConnectedAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConnectedAccount
	for rows.Next() {
		var i ConnectedAccount
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.Credentials,
			&i.SyncCursor,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnectionsForUser = `-- name: ListConnectionsForUser :many
select id, provider, status, sync_cursor, created_at
from connected_accounts
where user_id = $1::uuid
order by created_at desc
`

type ListConnectionsForUserRow struct {
	ID         int64      `db:"id" json:"id"`
	Provider   string     `db:"provider" json:"provider"`
	Status     string     `db:"status" json:"status"`
	SyncCursor *time.Time `db:"sync_cursor" json:"sync_cursor"`
	CreatedAt  time.Time  `db:"created_at" json:"created_at"`
}

func (q *Queries) ListConnectionsForUser(ctx context.Context, userID uuid.UUID) ([]ListConnectionsForUserRow, error) {
	rows, err := q.db.Query(ctx, listConnectionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConnectionsForUserRow
	for rows.Next() {
		var i ListConnectionsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Status,
			&i.SyncCursor,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConnectedAccountCursor = `-- name: UpdateConnectedAccountCursor :exec
update connected_accounts
set sync_cursor = $1::timestamptz,
    status      = coalesce($2::text, status)
where id = $3::bigint
`

type UpdateConnectedAccountCursorParams struct {
	SyncCursor *time.Time `db:"sync_cursor" json:"sync_cursor"`
	Status     *string    `db:"status" json:"status"`
	ID         int64      `db:"id" json:"id"`
}

func (q *Queries) UpdateConnectedAccountCursor(ctx context.Context, arg UpdateConnectedAccountCursorParams) error {
	_, err := q.db.Exec(ctx, updateConnectedAccountCursor, arg.SyncCursor, arg.Status, arg.ID)
	return err
}
