// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	null "null-core/internal/gen/null/v1"
)

const getAccountBalances = `-- name: GetAccountBalances :many
select
  a.id,
  a.name,
  a.account_type,
  a.anchor_currency as currency,
  COALESCE(
    (select t.balance_after_cents
     from transactions t
     where t.account_id = a.id
     order by t.tx_date desc, t.id desc
     limit 1),
    a.anchor_balance_cents
  ) as balance_cents
from accounts a
left join account_users au on a.id = au.account_id and au.user_id = $1::uuid
where (a.owner_id = $1::uuid or au.user_id is not null)
  and a.account_type != 6
order by
  case a.account_type
    when 1 then 1
    when 2 then 2
    when 3 then 3
    when 4 then 4
    when 5 then 5
    else 6
  end,
  balance_cents desc
`

type GetAccountBalancesRow struct {
	ID           int64            `db:"id" json:"id"`
	Name         string           `db:"name" json:"name"`
	AccountType  null.AccountType `db:"account_type" json:"account_type"`
	Currency     string           `db:"currency" json:"currency"`
	BalanceCents int64            `db:"balance_cents" json:"balance_cents"`
}

func (q *Queries) GetAccountBalances(ctx context.Context, userID uuid.UUID) ([]GetAccountBalancesRow, error) {
	rows, err := q.db.Query(ctx, getAccountBalances, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAccountBalancesRow
	for rows.Next() {
		var i GetAccountBalancesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AccountType,
			&i.Currency,
			&i.BalanceCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDashboardSummary = `-- name: GetDashboardSummary :one
select
  COUNT(distinct a.id)::bigint as total_accounts,
  COUNT(t.id)::bigint as total_transactions,
  COALESCE(SUM(case when t.tx_direction = 1 then t.tx_amount_cents else 0 end), 0)::bigint as total_income_cents,
  COALESCE(SUM(case when t.tx_direction = 2 then t.tx_amount_cents else 0 end), 0)::bigint as total_expense_cents,
  COUNT(distinct case when t.tx_date >= CURRENT_DATE - interval '30 days' then t.id end)::bigint as transactions_last_30_days,
  COUNT(distinct case when t.category_id is null then t.id end)::bigint as uncategorized_transactions
from accounts a
left join account_users au on a.id = au.account_id and au.user_id = $1::uuid
left join transactions t on a.id = t.account_id
where (a.owner_id = $1::uuid or au.user_id is not null)
  and a.account_type != 6
  and ($2::timestamptz is null or t.tx_date >= $2::timestamptz)
  and ($3::timestamptz is null or t.tx_date <= $3::timestamptz)
`

type GetDashboardSummaryParams struct {
	UserID uuid.UUID  `db:"user_id" json:"user_id"`
	Start  *time.Time `db:"start" json:"start"`
	End    *time.Time `db:"end" json:"end"`
}

type GetDashboardSummaryRow struct {
	TotalAccounts             int64 `db:"total_accounts" json:"total_accounts"`
	TotalTransactions         int64 `db:"total_transactions" json:"total_transactions"`
	TotalIncomeCents          int64 `db:"total_income_cents" json:"total_income_cents"`
	TotalExpenseCents         int64 `db:"total_expense_cents" json:"total_expense_cents"`
	TransactionsLast30Days    int64 `db:"transactions_last_30_days" json:"transactions_last_30_days"`
	UncategorizedTransactions int64 `db:"uncategorized_transactions" json:"uncategorized_transactions"`
}

func (q *Queries) GetDashboardSummary(ctx context.Context, arg GetDashboardSummaryParams) (GetDashboardSummaryRow, error) {
	row := q.db.QueryRow(ctx, getDashboardSummary, arg.UserID, arg.Start, arg.End)
	var i GetDashboardSummaryRow
	err := row.Scan(
		&i.TotalAccounts,
		&i.TotalTransactions,
		&i.TotalIncomeCents,
		&i.TotalExpenseCents,
		&i.TransactionsLast30Days,
		&i.UncategorizedTransactions,
	)
	return i, err
}

const getDashboardTrends = `-- name: GetDashboardTrends :many
select
  to_char(t.tx_date::date, 'YYYY-MM-DD') as date,
  SUM(case when t.tx_direction = 1 then t.tx_amount_cents else 0 end)::bigint as income_cents,
  SUM(case when t.tx_direction = 2 then t.tx_amount_cents else 0 end)::bigint as expense_cents
from transactions t
join accounts a on t.account_id = a.id
left join account_users au on a.id = au.account_id and au.user_id = $1::uuid
where (a.owner_id = $1::uuid or au.user_id is not null)
  and a.account_type != 6
  and ($2::timestamptz is null or t.tx_date >= $2::timestamptz)
  and ($3::timestamptz is null or t.tx_date <= $3::timestamptz)
group by date
order by date
`

type GetDashboardTrendsParams struct {
	UserID uuid.UUID  `db:"user_id" json:"user_id"`
	Start  *time.Time `db:"start" json:"start"`
	End    *time.Time `db:"end" json:"end"`
}

type GetDashboardTrendsRow struct {
	Date         string `db:"date" json:"date"`
	IncomeCents  int64  `db:"income_cents" json:"income_cents"`
	ExpenseCents int64  `db:"expense_cents" json:"expense_cents"`
}

func (q *Queries) GetDashboardTrends(ctx context.Context, arg GetDashboardTrendsParams) ([]GetDashboardTrendsRow, error) {
	rows, err := q.db.Query(ctx, getDashboardTrends, arg.UserID, arg.Start, arg.End)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDashboardTrendsRow
	for rows.Next() {
		var i GetDashboardTrendsRow
		if err := rows.Scan(&i.Date, &i.IncomeCents, &i.ExpenseCents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEarliestTransactionDate = `-- name: GetEarliestTransactionDate :one
select MIN(t.tx_date)::date as earliest_date
from transactions t
join accounts a on t.account_id = a.id
left join account_users au on a.id = au.account_id and au.user_id = $1::uuid
where (a.owner_id = $1::uuid or au.user_id is not null)
  and a.account_type != 6
`

func (q *Queries) GetEarliestTransactionDate(ctx context.Context, userID uuid.UUID) (time.Time, error) {
	row := q.db.QueryRow(ctx, getEarliestTransactionDate, userID)
	var earliest_date time.Time
	err := row.Scan(&earliest_date)
	return earliest_date, err
}

const getMonthlyComparison = `-- name: GetMonthlyComparison :many
select
  to_char(t.tx_date, 'YYYY-MM') as month,
  SUM(case when t.tx_direction = 1 then t.tx_amount_cents else 0 end)::bigint as income_cents,
  SUM(case when t.tx_direction = 2 then t.tx_amount_cents else 0 end)::bigint as expense_cents,
  SUM(case when t.tx_direction = 1 then t.tx_amount_cents else -t.tx_amount_cents end)::bigint as net_cents
from transactions t
join accounts a on t.account_id = a.id
left join account_users au on a.id = au.account_id and au.user_id = $1::uuid
where (a.owner_id = $1::uuid or au.user_id is not null)
  and a.account_type != 6
  and t.tx_date >= COALESCE($2::timestamptz, CURRENT_DATE - interval '12 months')
  and t.tx_date <= COALESCE($3::timestamptz, CURRENT_DATE)
group by month
order by month
`

type GetMonthlyComparisonParams struct {
	UserID uuid.UUID  `db:"user_id" json:"user_id"`
	Start  *time.Time `db:"start" json:"start"`
	End    *time.Time `db:"end" json:"end"`
}

type GetMonthlyComparisonRow struct {
	Month        string `db:"month" json:"month"`
	IncomeCents  int64  `db:"income_cents" json:"income_cents"`
	ExpenseCents int64  `db:"expense_cents" json:"expense_cents"`
	NetCents     int64  `db:"net_cents" json:"net_cents"`
}

func (q *Queries) GetMonthlyComparison(ctx context.Context, arg GetMonthlyComparisonParams) ([]GetMonthlyComparisonRow, error) {
	rows, err := q.db.Query(ctx, getMonthlyComparison, arg.UserID, arg.Start, arg.End)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMonthlyComparisonRow
	for rows.Next() {
		var i GetMonthlyComparisonRow
		if err := rows.Scan(
			&i.Month,
			&i.IncomeCents,
			&i.ExpenseCents,
			&i.NetCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNetWorthHistory = `-- name: GetNetWorthHistory :many
with date_series as (
  select
    generate_series(
      $1::timestamptz,
      $2::timestamptz,
      case $3::int
        when 1 then interval '1 day'
        when 2 then interval '1 week'
        when 3 then interval '1 month'
        else interval '1 day'
      end
    )::date as period_date
),
account_balances_at_date as (
  select
    ds.period_date,
    a.id as account_id,
    a.anchor_currency,
    CASE
      -- If there's a transaction on or before the period date, use its balance
      WHEN EXISTS (
        select 1 from transactions t
        where t.account_id = a.id and t.tx_date <= ds.period_date
      ) THEN (
        select t.balance_after_cents
        from transactions t
        where t.account_id = a.id and t.tx_date <= ds.period_date
        order by t.tx_date desc, t.id desc
        limit 1
      )
      -- If anchor date is on or before period date, use anchor balance
      WHEN a.anchor_date <= ds.period_date THEN a.anchor_balance_cents
      -- Otherwise, account didn't exist yet, so balance is 0
      ELSE 0
    END as balance_cents
  from date_series ds
  cross join accounts a
  left join account_users au on a.id = au.account_id and au.user_id = $4::uuid
  where (a.owner_id = $4::uuid or au.user_id is not null)
    and a.account_type != 6
)
select
  to_char(ab.period_date, 'YYYY-MM-DD') as date,
  SUM(ab.balance_cents)::bigint as net_worth_cents
from account_balances_at_date ab
group by ab.period_date
order by ab.period_date
`

type GetNetWorthHistoryParams struct {
	StartDate   time.Time `db:"start_date" json:"start_date"`
	EndDate     time.Time `db:"end_date" json:"end_date"`
	Granularity int32     `db:"granularity" json:"granularity"`
	UserID      uuid.UUID `db:"user_id" json:"user_id"`
}

type GetNetWorthHistoryRow struct {
	Date          string `db:"date" json:"date"`
	NetWorthCents int64  `db:"net_worth_cents" json:"net_worth_cents"`
}

func (q *Queries) GetNetWorthHistory(ctx context.Context, arg GetNetWorthHistoryParams) ([]GetNetWorthHistoryRow, error) {
	rows, err := q.db.Query(ctx, getNetWorthHistory,
		arg.StartDate,
		arg.EndDate,
		arg.Granularity,
		arg.UserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNetWorthHistoryRow
	for rows.Next() {
		var i GetNetWorthHistoryRow
		if err := rows.Scan(&i.Date, &i.NetWorthCents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopCategories = `-- name: GetTopCategories :many
select
  c.slug,
  c.color,
  COUNT(t.id)::bigint as transaction_count,
  SUM(t.tx_amount_cents)::bigint as total_amount_cents
from transactions t
join categories c on t.category_id = c.id
join accounts a on t.account_id = a.id
left join account_users au on a.id = au.account_id and au.user_id = $1::uuid
where (a.owner_id = $1::uuid or au.user_id is not null)
  and a.account_type != 6
  and t.tx_direction = 2
  and ($2::timestamptz is null or t.tx_date >= $2::timestamptz)
  and ($3::timestamptz is null or t.tx_date <= $3::timestamptz)
group by c.id, c.slug, c.color
order by total_amount_cents desc
limit COALESCE($4::int, 10)
`

type GetTopCategoriesParams struct {
	UserID uuid.UUID  `db:"user_id" json:"user_id"`
	Start  *time.Time `db:"start" json:"start"`
	End    *time.Time `db:"end" json:"end"`
	Limit  *int32     `db:"limit" json:"limit"`
}

type GetTopCategoriesRow struct {
	Slug             string `db:"slug" json:"slug"`
	Color            string `db:"color" json:"color"`
	TransactionCount int64  `db:"transaction_count" json:"transaction_count"`
	TotalAmountCents int64  `db:"total_amount_cents" json:"total_amount_cents"`
}

func (q *Queries) GetTopCategories(ctx context.Context, arg GetTopCategoriesParams) ([]GetTopCategoriesRow, error) {
	rows, err := q.db.Query(ctx, getTopCategories,
		arg.UserID,
		arg.Start,
		arg.End,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopCategoriesRow
	for rows.Next() {
		var i GetTopCategoriesRow
		if err := rows.Scan(
			&i.Slug,
			&i.Color,
			&i.TransactionCount,
			&i.TotalAmountCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopMerchants = `-- name: GetTopMerchants :many
select
  t.merchant,
  COUNT(t.id)::bigint as transaction_count,
  SUM(t.tx_amount_cents)::bigint as total_amount_cents,
  AVG(t.tx_amount_cents)::bigint as avg_amount_cents
from transactions t
join accounts a on t.account_id = a.id
left join account_users au on a.id = au.account_id and au.user_id = $1::uuid
where (a.owner_id = $1::uuid or au.user_id is not null)
  and a.account_type != 6
  and t.merchant is not null
  and t.tx_direction = 2
  and ($2::timestamptz is null or t.tx_date >= $2::timestamptz)
  and ($3::timestamptz is null or t.tx_date <= $3::timestamptz)
group by t.merchant
order by total_amount_cents desc
limit COALESCE($4::int, 10)
`

type GetTopMerchantsParams struct {
	UserID uuid.UUID  `db:"user_id" json:"user_id"`
	Start  *time.Time `db:"start" json:"start"`
	End    *time.Time `db:"end" json:"end"`
	Limit  *int32     `db:"limit" json:"limit"`
}

type GetTopMerchantsRow struct {
	Merchant         *string `db:"merchant" json:"merchant"`
	TransactionCount int64   `db:"transaction_count" json:"transaction_count"`
	TotalAmountCents int64   `db:"total_amount_cents" json:"total_amount_cents"`
	AvgAmountCents   int64   `db:"avg_amount_cents" json:"avg_amount_cents"`
}

func (q *Queries) GetTopMerchants(ctx context.Context, arg GetTopMerchantsParams) ([]GetTopMerchantsRow, error) {
	rows, err := q.db.Query(ctx, getTopMerchants,
		arg.UserID,
		arg.Start,
		arg.End,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopMerchantsRow
	for rows.Next() {
		var i GetTopMerchantsRow
		if err := rows.Scan(
			&i.Merchant,
			&i.TransactionCount,
			&i.TotalAmountCents,
			&i.AvgAmountCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
