// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
	null "null-core/internal/gen/null/v1"
)

type Account struct {
	ID                 int64            `db:"id" json:"id"`
	OwnerID            uuid.UUID        `db:"owner_id" json:"owner_id"`
	Name               string           `db:"name" json:"name"`
	Bank               string           `db:"bank" json:"bank"`
	AccountType        null.AccountType `db:"account_type" json:"account_type"`
	FriendlyName       *string          `db:"friendly_name" json:"friendly_name"`
	AnchorDate         time.Time        `db:"anchor_date" json:"anchor_date"`
	AnchorBalanceCents int64            `db:"anchor_balance_cents" json:"anchor_balance_cents"`
	AnchorCurrency     string           `db:"anchor_currency" json:"anchor_currency"`
	MainCurrency       string           `db:"main_currency" json:"main_currency"`
	Colors             []string         `db:"colors" json:"colors"`
	CreatedAt          time.Time        `db:"created_at" json:"created_at"`
	UpdatedAt          time.Time        `db:"updated_at" json:"updated_at"`
	Aliases            []string         `db:"aliases" json:"aliases"`
}

type AccountUser struct {
	AccountID int64     `db:"account_id" json:"account_id"`
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
	AddedAt   time.Time `db:"added_at" json:"added_at"`
}

type Category struct {
	ID        int64     `db:"id" json:"id"`
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
	Slug      string    `db:"slug" json:"slug"`
	Color     string    `db:"color" json:"color"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at"`
}

type Receipt struct {
	ID            int64              `db:"id" json:"id"`
	UserID        uuid.UUID          `db:"user_id" json:"user_id"`
	TransactionID *int64             `db:"transaction_id" json:"transaction_id"`
	ImagePath     string             `db:"image_path" json:"image_path"`
	Merchant      *string            `db:"merchant" json:"merchant"`
	ReceiptDate   *time.Time         `db:"receipt_date" json:"receipt_date"`
	Currency      *string            `db:"currency" json:"currency"`
	SubtotalCents *int64             `db:"subtotal_cents" json:"subtotal_cents"`
	TaxCents      *int64             `db:"tax_cents" json:"tax_cents"`
	TotalCents    *int64             `db:"total_cents" json:"total_cents"`
	Confidence    *float32           `db:"confidence" json:"confidence"`
	Status        null.ReceiptStatus `db:"status" json:"status"`
	CreatedAt     time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time          `db:"updated_at" json:"updated_at"`
	ImageHash     *string            `db:"image_hash" json:"image_hash"`
	ImageTakenAt  *time.Time         `db:"image_taken_at" json:"image_taken_at"`
}

type ReceiptItem struct {
	ID             int64     `db:"id" json:"id"`
	ReceiptID      int64     `db:"receipt_id" json:"receipt_id"`
	RawName        string    `db:"raw_name" json:"raw_name"`
	Name           *string   `db:"name" json:"name"`
	Quantity       float64   `db:"quantity" json:"quantity"`
	UnitPriceCents int64     `db:"unit_price_cents" json:"unit_price_cents"`
	UnitCurrency   string    `db:"unit_currency" json:"unit_currency"`
	SortOrder      int32     `db:"sort_order" json:"sort_order"`
	CreatedAt      time.Time `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time `db:"updated_at" json:"updated_at"`
}

type Transaction struct {
	ID                  int64                     `db:"id" json:"id"`
	AccountID           int64                     `db:"account_id" json:"account_id"`
	EmailID             *string                   `db:"email_id" json:"email_id"`
	TxDate              time.Time                 `db:"tx_date" json:"tx_date"`
	TxAmountCents       int64                     `db:"tx_amount_cents" json:"tx_amount_cents"`
	TxCurrency          string                    `db:"tx_currency" json:"tx_currency"`
	TxDirection         null.TransactionDirection `db:"tx_direction" json:"tx_direction"`
	TxDesc              *string                   `db:"tx_desc" json:"tx_desc"`
	BalanceAfterCents   *int64                    `db:"balance_after_cents" json:"balance_after_cents"`
	BalanceCurrency     *string                   `db:"balance_currency" json:"balance_currency"`
	Merchant            *string                   `db:"merchant" json:"merchant"`
	CategoryID          *int64                    `db:"category_id" json:"category_id"`
	CategoryManuallySet bool                      `db:"category_manually_set" json:"category_manually_set"`
	MerchantManuallySet bool                      `db:"merchant_manually_set" json:"merchant_manually_set"`
	Suggestions         []string                  `db:"suggestions" json:"suggestions"`
	UserNotes           *string                   `db:"user_notes" json:"user_notes"`
	ForeignAmountCents  *int64                    `db:"foreign_amount_cents" json:"foreign_amount_cents"`
	ForeignCurrency     *string                   `db:"foreign_currency" json:"foreign_currency"`
	ExchangeRate        *float64                  `db:"exchange_rate" json:"exchange_rate"`
	CreatedAt           time.Time                 `db:"created_at" json:"created_at"`
	UpdatedAt           time.Time                 `db:"updated_at" json:"updated_at"`
}

type TransactionRule struct {
	RuleID        uuid.UUID  `db:"rule_id" json:"rule_id"`
	UserID        uuid.UUID  `db:"user_id" json:"user_id"`
	RuleName      string     `db:"rule_name" json:"rule_name"`
	CategoryID    *int64     `db:"category_id" json:"category_id"`
	Merchant      *string    `db:"merchant" json:"merchant"`
	Conditions    []byte     `db:"conditions" json:"conditions"`
	LogicOperator string     `db:"logic_operator" json:"logic_operator"`
	IsActive      *bool      `db:"is_active" json:"is_active"`
	PriorityOrder int32      `db:"priority_order" json:"priority_order"`
	RuleSource    string     `db:"rule_source" json:"rule_source"`
	CreatedAt     time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time  `db:"updated_at" json:"updated_at"`
	LastAppliedAt *time.Time `db:"last_applied_at" json:"last_applied_at"`
	TimesApplied  *int32     `db:"times_applied" json:"times_applied"`
}

type User struct {
	ID              uuid.UUID `db:"id" json:"id"`
	Email           string    `db:"email" json:"email"`
	DisplayName     *string   `db:"display_name" json:"display_name"`
	PrimaryCurrency string    `db:"primary_currency" json:"primary_currency"`
	Timezone        string    `db:"timezone" json:"timezone"`
	CreatedAt       time.Time `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time `db:"updated_at" json:"updated_at"`
}
