// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: receipts.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	null "null-core/internal/gen/null/v1"
)

const createReceipt = `-- name: CreateReceipt :one
INSERT INTO receipts (
  user_id,
  image_path,
  status
)
VALUES (
  $1::uuid,
  $2::text,
  $3::smallint
)
RETURNING id, user_id, transaction_id, image_path, merchant, receipt_date, currency, subtotal_cents, tax_cents, total_cents, confidence, status, created_at, updated_at
`

type CreateReceiptParams struct {
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
	ImagePath string    `db:"image_path" json:"image_path"`
	Status    int16     `db:"status" json:"status"`
}

func (q *Queries) CreateReceipt(ctx context.Context, arg CreateReceiptParams) (Receipt, error) {
	row := q.db.QueryRow(ctx, createReceipt, arg.UserID, arg.ImagePath, arg.Status)
	var i Receipt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TransactionID,
		&i.ImagePath,
		&i.Merchant,
		&i.ReceiptDate,
		&i.Currency,
		&i.SubtotalCents,
		&i.TaxCents,
		&i.TotalCents,
		&i.Confidence,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReceiptItem = `-- name: CreateReceiptItem :one
INSERT INTO receipt_items (
  receipt_id,
  raw_name,
  name,
  quantity,
  unit_price_cents,
  unit_currency,
  sort_order
)
VALUES (
  $1::bigint,
  $2::text,
  $3::text,
  $4::double precision,
  $5::bigint,
  $6::char(3),
  $7::int
)
RETURNING id, receipt_id, raw_name, name, quantity, unit_price_cents, unit_currency, sort_order, created_at, updated_at
`

type CreateReceiptItemParams struct {
	ReceiptID      int64   `db:"receipt_id" json:"receipt_id"`
	RawName        string  `db:"raw_name" json:"raw_name"`
	Name           *string `db:"name" json:"name"`
	Quantity       float64 `db:"quantity" json:"quantity"`
	UnitPriceCents int64   `db:"unit_price_cents" json:"unit_price_cents"`
	UnitCurrency   string  `db:"unit_currency" json:"unit_currency"`
	SortOrder      int32   `db:"sort_order" json:"sort_order"`
}

func (q *Queries) CreateReceiptItem(ctx context.Context, arg CreateReceiptItemParams) (ReceiptItem, error) {
	row := q.db.QueryRow(ctx, createReceiptItem,
		arg.ReceiptID,
		arg.RawName,
		arg.Name,
		arg.Quantity,
		arg.UnitPriceCents,
		arg.UnitCurrency,
		arg.SortOrder,
	)
	var i ReceiptItem
	err := row.Scan(
		&i.ID,
		&i.ReceiptID,
		&i.RawName,
		&i.Name,
		&i.Quantity,
		&i.UnitPriceCents,
		&i.UnitCurrency,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteReceipt = `-- name: DeleteReceipt :exec
DELETE FROM receipts
WHERE id = $1::bigint
  AND user_id = $2::uuid
`

type DeleteReceiptParams struct {
	ID     int64     `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteReceipt(ctx context.Context, arg DeleteReceiptParams) error {
	_, err := q.db.Exec(ctx, deleteReceipt, arg.ID, arg.UserID)
	return err
}

const deleteReceiptItemsByReceipt = `-- name: DeleteReceiptItemsByReceipt :exec
DELETE FROM receipt_items
WHERE receipt_id = $1::bigint
`

func (q *Queries) DeleteReceiptItemsByReceipt(ctx context.Context, receiptID int64) error {
	_, err := q.db.Exec(ctx, deleteReceiptItemsByReceipt, receiptID)
	return err
}

const findReceiptLinkCandidates = `-- name: FindReceiptLinkCandidates :many
SELECT
  t.id,
  t.account_id,
  t.tx_date,
  t.tx_amount_cents,
  t.tx_currency,
  t.merchant,
  COALESCE(a.friendly_name, a.name) AS account_display_name,
  CASE
    WHEN $1::date IS NOT NULL
    THEN ABS(t.tx_date::date - $1::date)
    ELSE NULL
  END AS date_diff_days
FROM transactions t
JOIN accounts a ON t.account_id = a.id
LEFT JOIN account_users au ON a.id = au.account_id AND au.user_id = $2::uuid
WHERE (a.owner_id = $2::uuid OR au.user_id IS NOT NULL)
  AND t.tx_amount_cents BETWEEN $3::bigint - 50 AND $3::bigint + 50
  AND t.tx_currency = $4::char(3)
  AND t.tx_direction = 2::smallint
  AND NOT EXISTS (
    SELECT 1 FROM receipts r
    WHERE r.transaction_id = t.id
  )
ORDER BY
  CASE
    WHEN $1::date IS NOT NULL
    THEN ABS(t.tx_date::date - $1::date)
    ELSE 0
  END ASC,
  t.tx_date DESC
LIMIT 10
`

type FindReceiptLinkCandidatesParams struct {
	ReceiptDate *time.Time `db:"receipt_date" json:"receipt_date"`
	UserID      uuid.UUID  `db:"user_id" json:"user_id"`
	AmountCents int64      `db:"amount_cents" json:"amount_cents"`
	Currency    string     `db:"currency" json:"currency"`
}

type FindReceiptLinkCandidatesRow struct {
	ID                 int64       `db:"id" json:"id"`
	AccountID          int64       `db:"account_id" json:"account_id"`
	TxDate             time.Time   `db:"tx_date" json:"tx_date"`
	TxAmountCents      int64       `db:"tx_amount_cents" json:"tx_amount_cents"`
	TxCurrency         string      `db:"tx_currency" json:"tx_currency"`
	Merchant           *string     `db:"merchant" json:"merchant"`
	AccountDisplayName string      `db:"account_display_name" json:"account_display_name"`
	DateDiffDays       interface{} `db:"date_diff_days" json:"date_diff_days"`
}

func (q *Queries) FindReceiptLinkCandidates(ctx context.Context, arg FindReceiptLinkCandidatesParams) ([]FindReceiptLinkCandidatesRow, error) {
	rows, err := q.db.Query(ctx, findReceiptLinkCandidates,
		arg.ReceiptDate,
		arg.UserID,
		arg.AmountCents,
		arg.Currency,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindReceiptLinkCandidatesRow
	for rows.Next() {
		var i FindReceiptLinkCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TxDate,
			&i.TxAmountCents,
			&i.TxCurrency,
			&i.Merchant,
			&i.AccountDisplayName,
			&i.DateDiffDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingReceipts = `-- name: GetPendingReceipts :many
SELECT id, user_id, transaction_id, image_path, merchant, receipt_date, currency, subtotal_cents, tax_cents, total_cents, confidence, status, created_at, updated_at
FROM receipts
WHERE status = 1
ORDER BY created_at ASC
LIMIT 20
`

func (q *Queries) GetPendingReceipts(ctx context.Context) ([]Receipt, error) {
	rows, err := q.db.Query(ctx, getPendingReceipts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Receipt
	for rows.Next() {
		var i Receipt
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TransactionID,
			&i.ImagePath,
			&i.Merchant,
			&i.ReceiptDate,
			&i.Currency,
			&i.SubtotalCents,
			&i.TaxCents,
			&i.TotalCents,
			&i.Confidence,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReceipt = `-- name: GetReceipt :one
SELECT id, user_id, transaction_id, image_path, merchant, receipt_date, currency, subtotal_cents, tax_cents, total_cents, confidence, status, created_at, updated_at
FROM receipts
WHERE id = $1::bigint
  AND user_id = $2::uuid
`

type GetReceiptParams struct {
	ID     int64     `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetReceipt(ctx context.Context, arg GetReceiptParams) (Receipt, error) {
	row := q.db.QueryRow(ctx, getReceipt, arg.ID, arg.UserID)
	var i Receipt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TransactionID,
		&i.ImagePath,
		&i.Merchant,
		&i.ReceiptDate,
		&i.Currency,
		&i.SubtotalCents,
		&i.TaxCents,
		&i.TotalCents,
		&i.Confidence,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReceiptItems = `-- name: ListReceiptItems :many
SELECT id, receipt_id, raw_name, name, quantity, unit_price_cents, unit_currency, sort_order, created_at, updated_at
FROM receipt_items
WHERE receipt_id = $1::bigint
ORDER BY sort_order ASC, id ASC
`

func (q *Queries) ListReceiptItems(ctx context.Context, receiptID int64) ([]ReceiptItem, error) {
	rows, err := q.db.Query(ctx, listReceiptItems, receiptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReceiptItem
	for rows.Next() {
		var i ReceiptItem
		if err := rows.Scan(
			&i.ID,
			&i.ReceiptID,
			&i.RawName,
			&i.Name,
			&i.Quantity,
			&i.UnitPriceCents,
			&i.UnitCurrency,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceipts = `-- name: ListReceipts :many
SELECT
  r.id, r.user_id, r.transaction_id, r.image_path, r.merchant, r.receipt_date, r.currency, r.subtotal_cents, r.tax_cents, r.total_cents, r.confidence, r.status, r.created_at, r.updated_at,
  count(*) OVER() AS total_count
FROM receipts r
WHERE r.user_id = $1::uuid
  AND (
    $2::smallint IS NULL
    OR r.status = $2::smallint
  )
  AND (
    $3::boolean IS NULL
    OR ($3::boolean = true AND r.transaction_id IS NULL)
  )
  AND (
    $4::date IS NULL
    OR r.receipt_date >= $4::date
  )
  AND (
    $5::date IS NULL
    OR r.receipt_date <= $5::date
  )
ORDER BY r.created_at DESC, r.id DESC
LIMIT COALESCE($7::int, 50)
OFFSET COALESCE($6::int, 0)
`

type ListReceiptsParams struct {
	UserID       uuid.UUID  `db:"user_id" json:"user_id"`
	Status       *int16     `db:"status" json:"status"`
	UnlinkedOnly *bool      `db:"unlinked_only" json:"unlinked_only"`
	StartDate    *time.Time `db:"start_date" json:"start_date"`
	EndDate      *time.Time `db:"end_date" json:"end_date"`
	Off          *int32     `db:"off" json:"off"`
	Lim          *int32     `db:"lim" json:"lim"`
}

type ListReceiptsRow struct {
	ID            int64              `db:"id" json:"id"`
	UserID        uuid.UUID          `db:"user_id" json:"user_id"`
	TransactionID *int64             `db:"transaction_id" json:"transaction_id"`
	ImagePath     string             `db:"image_path" json:"image_path"`
	Merchant      *string            `db:"merchant" json:"merchant"`
	ReceiptDate   *time.Time         `db:"receipt_date" json:"receipt_date"`
	Currency      *string            `db:"currency" json:"currency"`
	SubtotalCents *int64             `db:"subtotal_cents" json:"subtotal_cents"`
	TaxCents      *int64             `db:"tax_cents" json:"tax_cents"`
	TotalCents    *int64             `db:"total_cents" json:"total_cents"`
	Confidence    *float32           `db:"confidence" json:"confidence"`
	Status        null.ReceiptStatus `db:"status" json:"status"`
	CreatedAt     time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time          `db:"updated_at" json:"updated_at"`
	TotalCount    int64              `db:"total_count" json:"total_count"`
}

func (q *Queries) ListReceipts(ctx context.Context, arg ListReceiptsParams) ([]ListReceiptsRow, error) {
	rows, err := q.db.Query(ctx, listReceipts,
		arg.UserID,
		arg.Status,
		arg.UnlinkedOnly,
		arg.StartDate,
		arg.EndDate,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReceiptsRow
	for rows.Next() {
		var i ListReceiptsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TransactionID,
			&i.ImagePath,
			&i.Merchant,
			&i.ReceiptDate,
			&i.Currency,
			&i.SubtotalCents,
			&i.TaxCents,
			&i.TotalCents,
			&i.Confidence,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReceipt = `-- name: UpdateReceipt :one
UPDATE receipts
SET
  transaction_id = coalesce($1::bigint, transaction_id),
  merchant       = coalesce($2::text, merchant),
  receipt_date   = coalesce($3::date, receipt_date),
  currency       = coalesce($4::char(3), currency),
  subtotal_cents = coalesce($5::bigint, subtotal_cents),
  tax_cents      = coalesce($6::bigint, tax_cents),
  total_cents    = coalesce($7::bigint, total_cents),
  confidence     = coalesce($8::real, confidence),
  status         = coalesce($9::smallint, status)
WHERE id = $10::bigint
  AND user_id = $11::uuid
RETURNING id, user_id, transaction_id, image_path, merchant, receipt_date, currency, subtotal_cents, tax_cents, total_cents, confidence, status, created_at, updated_at
`

type UpdateReceiptParams struct {
	TransactionID *int64     `db:"transaction_id" json:"transaction_id"`
	Merchant      *string    `db:"merchant" json:"merchant"`
	ReceiptDate   *time.Time `db:"receipt_date" json:"receipt_date"`
	Currency      *string    `db:"currency" json:"currency"`
	SubtotalCents *int64     `db:"subtotal_cents" json:"subtotal_cents"`
	TaxCents      *int64     `db:"tax_cents" json:"tax_cents"`
	TotalCents    *int64     `db:"total_cents" json:"total_cents"`
	Confidence    *float32   `db:"confidence" json:"confidence"`
	Status        *int16     `db:"status" json:"status"`
	ID            int64      `db:"id" json:"id"`
	UserID        uuid.UUID  `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateReceipt(ctx context.Context, arg UpdateReceiptParams) (Receipt, error) {
	row := q.db.QueryRow(ctx, updateReceipt,
		arg.TransactionID,
		arg.Merchant,
		arg.ReceiptDate,
		arg.Currency,
		arg.SubtotalCents,
		arg.TaxCents,
		arg.TotalCents,
		arg.Confidence,
		arg.Status,
		arg.ID,
		arg.UserID,
	)
	var i Receipt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TransactionID,
		&i.ImagePath,
		&i.Merchant,
		&i.ReceiptDate,
		&i.Currency,
		&i.SubtotalCents,
		&i.TaxCents,
		&i.TotalCents,
		&i.Confidence,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
