-- +goose Up
CREATE TABLE connected_accounts (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  provider     TEXT NOT NULL CHECK (provider IN ('wise', 'snaptrade')),
  credentials  BYTEA NOT NULL,
  sync_cursor  TIMESTAMPTZ,
  status       TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled', 'broken')),
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, provider)
);

CREATE TRIGGER trg_connected_accounts_update
  BEFORE UPDATE ON connected_accounts
  FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE INDEX idx_connected_accounts_active
  ON connected_accounts(user_id) WHERE status = 'active';

-- +goose Down
DROP TABLE IF EXISTS connected_accounts;
